---
title: "Almond Yield Model"
author: "Almond Group C"
date: "4/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(knitr)
library(kableExtra)

source('yield_model.R')
```

```{r load_data, message = FALSE}
# Read in climate data
clim <- read_delim("./clim.txt", delim=" ")
```

```{r model_yield_table}
model_results <- yield_model(clim)

kable(model_results %>% 
        rename(Year = year, "Almond Yield Anomaly (ton/acre)" = almond_yield), 
      digits=4,
      caption = "Modeled Almond Yield Anomaly 1989-2010",
      format = "html",
      table.attr = "style='width:50%;'") %>% 
  kable_classic() %>% 
  kable_styling(bootstrap_options = c("striped", "hover"),
                position = "left")
```

```{r model_yield_plot, warning = FALSE}
ggplot(data = model_results, aes(x = year, y = almond_yield)) +
  geom_line() +
  geom_point() +
  theme_light() +
  labs(x = "Year",
       y = "Almond Yield Anomaly (ton/acre)",
       title = "Modeled Almond Yield Anomaly 1989-2010")
```

